# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hungarian-ocr',
                'doc_host': 'https://jchenj.github.io',
                'git_url': 'https://github.com/jchenj/hungarian-ocr',
                'lib_path': 'hungarian_ocr'},
  'syms': {'hungarian_ocr.core': {'hungarian_ocr.core.foo': ('core.html#foo', 'hungarian_ocr/core.py')}}}
