"""Core functionality for secure processing and text extraction from medical documents. This module handles the initial stage of document processing - converting image-based documents into machine-readable text while maintaining privacy and security considerations."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['say_hello', 'doc_loading', 'foo']

# %% ../nbs/00_core.ipynb 3
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# %% ../nbs/00_core.ipynb 6
def doc_loading(photo):
    "Loads the photo"
    pass

# %% ../nbs/00_core.ipynb 7
def foo(): pass
